const MEDICAL_SPECIALTIES = Object.freeze([
  'Anesthesiology',
  'Cardiac Surgery',
  'Cardiology',
  'Critical Care Medicine',
  'Dermatology',
  'Emergency Medicine',
  'Endocrinology',
  'Family Medicine',
  'Gastroenterology',
  'General Surgery',
  'Geriatric Medicine',
  'Hematology',
  'Infectious Diseases',
  'Internal Medicine',
  'Medical Genetics',
  'Nephrology',
  'Neurology',
  'Neurosurgery',
  'Nuclear Medicine',
  'Obstetrics and Gynecology',
  'Oncology',
  'Ophthalmology',
  'Orthopedic Surgery',
  'Otolaryngology',
  'Palliative Medicine',
  'Pathology',
  'Pediatrics',
  'Physical Medicine and Rehabilitation',
  'Plastic Surgery',
  'Psychiatry',
  'Public Health and Preventive Medicine',
  'Radiation Oncology',
  'Radiology',
  'Respirology',
  'Rheumatology',
  'Thoracic Surgery',
  'Urology',
  'Vascular Surgery',
  'Other',
]);

function isAllowedSpecialty(value) {
  return typeof value === 'string' && MEDICAL_SPECIALTIES.includes(value);
}

module.exports = { MEDICAL_SPECIALTIES, isAllowedSpecialty };
